# Generated by Django 5.2.15 on 2026-07-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=180)),
                ('issuer', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(default='Backend', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
